# Site settings
title: 无羽的博客|nonefly
tagline: 随风而动－＋－随梦而行
email: 844059694@qq.com
description:
 － Doing Follow the Heart     
 － Going After the Dream
baseurl: ""
url: "http://nonefly.com"
logourl: /assets/images/logo.png # Site logo
author: "nonefly"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#B40486"
  social: 
    github: nonefly
    twitter: zy_nonefly
    #facebook: 
    #gplus: 
    #dribble: 
    #pinterest: 

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus: nonefly

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key:
  google_webmaster_key: 

markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
